package ru.openunity.hunterhint.ui.enums

import androidx.annotation.StringRes
import ru.openunity.hunterhint.R

enum class HuntingResources(val id: Int, val type: Int, @StringRes val stringRes: Int) {
    HOG(0, 0, R.string.hog),
    MUSK_DEER(1, 0, R.string.musk_deer),
    WILD_REINDEER(2, 0, R.string.wild_reindeer),
    ROE_DEER(3, 0, R.string.roe_deer),
    MOOSE(4, 0, R.string.moose),
    THE_RED_DEER(5, 0, R.string.the_red_deer),
    SPOTTED_DEER(6, 0, R.string.spotted_deer),
    DOE(7, 0, R.string.doe),
    MUSK_OX(8, 0, R.string.musk_ox),
    MOUFFLON(9, 0, R.string.moufflon),
    SAIGA_ANTELOPE(10, 0, R.string.saiga_antelope),
    CHAMOIS(11, 0, R.string.chamois),
    SIBERIAN_MOUNTAIN_GOAT(12, 0, R.string.siberian_mountain_goat),
    TOURS(13, 0, R.string.tours),
    THE_SNOW_SHEEP(14, 0, R.string.the_snow_sheep),
    HYBRIDS_OF_BISON_WITH_BISON_OR_LIVESTOCK(
        15,
        0,
        R.string.hybrids_of_bison_with_bison_or_livestock
    ),
    BEARS(16, 0, R.string.bears),
    WOLF(17, 0, R.string.wolf),
    THE_JACKAL(18, 0, R.string.the_jackal),
    THE_FOX(19, 0, R.string.the_fox),
    CORSAC(20, 0, R.string.corsac),
    ARCTIC_FOX(21, 0, R.string.arctic_fox),
    RACCOON_DOG(22, 0, R.string.raccoon_dog),
    RACCOON_POLOSUN(23, 0, R.string.raccoon_polosun),
    LYNX(24, 0, R.string.lynx),
    WOLVERINE(25, 0, R.string.wolverine),
    BADGER(26, 0, R.string.badger),
    MARTENS(27, 0, R.string.martens),
    SABLE(28, 0, R.string.sable),
    KHARZA(29, 0, R.string.kharza),
    WILD_CATS(30, 0, R.string.wild_cats),
    TENDERNESS(31, 0, R.string.tenderness),
    ERMINE(32, 0, R.string.ermine),
    SOLONGOY(33, 0, R.string.solongoy),
    COLUMNS(34, 0, R.string.columns),
    HORI(35, 0, R.string.hori),
    MINKS(36, 0, R.string.minks),
    OTTER(37, 0, R.string.otter),
    HARES(38, 0, R.string.hares),
    WILD_RABBIT(39, 0, R.string.wild_rabbit),
    BEAVERS(40, 0, R.string.beavers),
    GROUNDHOGS(41, 0, R.string.groundhogs),
    GOPHERS(42, 0, R.string.gophers),
    MOLES(43, 0, R.string.moles),
    CHIPMUNKS(44, 0, R.string.chipmunks),
    THE_FLYING_MAN(45, 0, R.string.the_flying_man),
    SQUIRRELS(46, 0, R.string.squirrels),
    HAMSTERS(47, 0, R.string.hamsters),
    MUSKRAT(48, 0, R.string.muskrat),
    THE_WATER_VOLE(49, 0, R.string.the_water_vole),
    GEESE(50, 0, R.string.geese),
    BARRACKS(51, 0, R.string.barracks),
    DUCKS(52, 0, R.string.ducks),
    CAPERCAILLIE(53, 0, R.string.capercaillie),
    BLACKCOCK(54, 0, R.string.blackcock),
    GROUSE(55, 0, R.string.grouse),
    PARTRIDGES(56, 0, R.string.partridges),
    QUAIL(57, 0, R.string.quail),
    CUPCAKE(58, 0, R.string.cupcake),
    PHEASANTS(59, 0, R.string.pheasants),
    ULARY(60, 0, R.string.ulary),
    THE_SHEPHERD_BOY(61, 0, R.string.the_shepherd_boy),
    AN_ORDINARY_POGONISH(62, 0, R.string.an_ordinary_pogonish),
    CRAKE(63, 0, R.string.crake),
    MOORHEN(64, 0, R.string.moorhen),
    COOT(65, 0, R.string.coot),
    LAPWING(66, 0, R.string.lapwing),
    THULES(67, 0, R.string.thules),
    CRUNCH(68, 0, R.string.crunch),
    THE_STONE_COOK(69, 0, R.string.the_stone_cook),
    TURUKHTAN(70, 0, R.string.turukhtan),
    HERBALIST(71, 0, R.string.herbalist),
    SNAIL(72, 0, R.string.snail),
    MORODUNKA(73, 0, R.string.morodunka),
    SPINDLES(74, 0, R.string.spindles),
    CURLEWS(75, 0, R.string.curlews),
    SNIPE(76, 0, R.string.snipe),
    THE_HOLLOW(77, 0, R.string.the_hollow),
    GARSHNEP(78, 0, R.string.garshnep),
    WOODCOCK(79, 0, R.string.woodcock),
    SAJA(80, 0, R.string.saja),
    PIGEONS(81, 0, R.string.pigeons),
    TURTLEDOVES(82, 0, R.string.turtledoves)
}

fun getResourcesById(id: Int): HuntingResources {
    return HuntingResources.entries.find { it.id == id } ?: HuntingResources.HOG
}