package ru.openunity.hunterhint.ui.registration

import ru.openunity.hunterhint.R

enum class Gender(val stringResourceId: Int, val gCode: Int) {
    MALE(R.string.male, 0), FEMALE(R.string.female, 1)
}

enum class Month(val days: Int, val stringResourceId: Int, val mCode: Int) {
    JANUARY(31, R.string.january, 1), FEBRUARY(29, R.string.february, 2), MARCH(
        31, R.string.march,3
    ),
    APRIL(30, R.string.april, 4), MAY(31, R.string.may, 5), JUNE(30, R.string.june, 6), JULY(
        31, R.string.july, 7
    ),
    AUGUST(31, R.string.august, 8), SEPTEMBER(30, R.string.september, 9), OCTOBER(
        31, R.string.october,10
    ),
    NOVEMBER(30, R.string.november,11), DECEMBER(31, R.string.december,12)
}

enum class Country(val countryName: String, val internationalCountryCode: String, val fIPS: String, val numberFormat: String, val cCode: Int) {
    JAMAICA("Jamaica","1876","JM","XXX XXXX", 0),
    SAINT_KITTS_NEVIS("Saint Kitts & Nevis","1869","KN","XXX XXXX", 1),
    TRINIDAD_TOBAGO("Trinidad & Tobago","1868","TT","XXX XXXX", 2),
    SAINT_VINCENT_THE_GRENADINES("Saint Vincent & the Grenadines","1784","VC","XXX XXXX", 3),
    DOMINICA("Dominica","1767","DM","XXX XXXX", 4),
    SAINT_LUCIA("Saint Lucia","1758","LC","XXX XXXX", 5),
    SINT_MAARTEN("Sint Maarten","1721","SX","XXX XXXX", 6),
    AMERICAN_SAMOA("American Samoa","1684","AS","XXX XXXX", 7),
    GUAM("Guam","1671","GU","XXX XXXX", 8),
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands","1670","MP","XXX XXXX", 9),
    MONTSERRAT("Montserrat","1664","MS","XXX XXXX", 10),
    TURKS_CAICOS_ISLANDS("Turks & Caicos Islands","1649","TC","XXX XXXX", 11),
    GRENADA("Grenada","1473","GD","XXX XXXX", 12),
    BERMUDA("Bermuda","1441","BM","XXX XXXX", 13),
    CAYMAN_ISLANDS("Cayman Islands","1345","KY","XXX XXXX", 14),
    US_VIRGIN_ISLANDS("US Virgin Islands","1340","VI","XXX XXXX", 15),
    BRITISH_VIRGIN_ISLANDS("British Virgin Islands","1284","VG","XXX XXXX", 16),
    ANTIGUA_BARBUDA("Antigua & Barbuda","1268","AG","XXX XXXX", 17),
    ANGUILLA("Anguilla","1264","AI","XXX XXXX", 18),
    BARBADOS("Barbados","1246","BB","XXX XXXX", 19),
    BAHAMAS("Bahamas","1242","BS","XXX XXXX", 20),
    UZBEKISTAN("Uzbekistan","998","UZ","XX XXXXXXX", 21),
    KYRGYZSTAN("Kyrgyzstan","996","KG","XXX XXXXXX", 22),
    GEORGIA("Georgia","995","GE","XXX XXX XXX", 23),
    AZERBAIJAN("Azerbaijan","994","AZ","XX XXX XXXX", 24),
    TURKMENISTAN("Turkmenistan","993","TM","XX XXXXXX", 25),
    TAJIKISTAN("Tajikistan","992","TJ","XX XXX XXXX", 26),
    NEPAL("Nepal","977","NP","XX XXXX XXXX", 27),
    MONGOLIA("Mongolia","976","MN","XX XX XXXX", 28),
    BHUTAN("Bhutan","975","BT","XX XXX XXX", 29),
    QATAR("Qatar","974","QA","XX XXX XXX", 30),
    BAHRAIN("Bahrain","973","BH","XXXX XXXX", 31),
    ISRAEL("Israel","972","IL","XX XXX XXXX", 32),
    UNITED_ARAB_EMIRATES("United Arab Emirates","971","AE","XX XXX XXXX", 33),
    PALESTINE("Palestine","970","PS","XXX XX XXXX", 34),
    OMAN("Oman","968","OM","XXXX XXXX", 35),
    YEMEN("Yemen","967","YE","XXX XXX XXX", 36),
    SAUDI_ARABIA("Saudi Arabia","966","SA","XX XXX XXXX", 37),
    KUWAIT("Kuwait","965","KW","XXXX XXXX", 38),
    IRAQ("Iraq","964","IQ","XXX XXX XXXX", 39),
    SYRIA("Syria","963","SY","XXX XXX XXX", 40),
    JORDAN("Jordan","962","JO","X XXXX XXXX", 41),
    LEBANON("Lebanon","961","LB","", 42),
    MALDIVES("Maldives","960","MV","XXX XXXX", 43),
    TAIWAN("Taiwan","886","TW","XXX XXX XXX", 44),
    INTERNATIONAL_NETWORKS_883("International Networks","883","GO","", 45),
    INTERNATIONAL_NETWORKS_882("International Networks","882","GO","", 46),
    GLOBAL_MOBILE_SATELLITE("Global Mobile Satellite","881","GO","", 47),
    BANGLADESH("Bangladesh","880","BD","", 48),
    LAOS("Laos","856","LA","XX XX XXX XXX", 49),
    CAMBODIA("Cambodia","855","KH","", 50),
    MACAU("Macau","853","MO","XXXX XXXX", 51),
    HONG_KONG("Hong Kong","852","HK","X XXX XXXX", 52),
    NORTH_KOREA("North Korea","850","KP","", 53),
    MARSHALL_ISLANDS("Marshall Islands","692","MH","", 54),
    MICRONESIA("Micronesia","691","FM","", 55),
    TOKELAU("Tokelau","690","TK","", 56),
    FRENCH_POLYNESIA("French Polynesia","689","PF","", 57),
    TUVALU("Tuvalu","688","TV","", 58),
    NEW_CALEDONIA("New Caledonia","687","NC","", 59),
    KIRIBATI("Kiribati","686","KI","", 60),
    SAMOA("Samoa","685","WS","", 61),
    NIUE("Niue","683","NU","", 62),
    COOK_ISLANDS("Cook Islands","682","CK","", 63),
    WALLIS_FUTUNA("Wallis & Futuna","681","WF","", 64),
    PALAU("Palau","680","PW","", 65),
    FIJI("Fiji","679","FJ","", 66),
    VANUATU("Vanuatu","678","VU","", 67),
    SOLOMON_ISLANDS("Solomon Islands","677","SB","", 68),
    TONGA("Tonga","676","TO","", 69),
    PAPUA_NEW_GUINEA("Papua New Guinea","675","PG","", 70),
    NAURU("Nauru","674","NR","", 71),
    BRUNEI_DARUSSALAM("Brunei Darussalam","673","BN","XXX XXXX", 72),
    NORFOLK_ISLAND("Norfolk Island","672","NF","", 73),
    TIMOR_LESTE("Timor-Leste","670","TL","", 74),
    BONAIRE_SINT_EUSTATIUS_SABA("Bonaire, Sint Eustatius & Saba","599","BQ","", 75),
    CURACAO("Curaçao","599","CW","", 76),
    URUGUAY("Uruguay","598","UY","X XXX XXXX", 77),
    SURINAME("Suriname","597","SR","XXX XXXX", 78),
    MARTINIQUE("Martinique","596","MQ","", 79),
    PARAGUAY("Paraguay","595","PY","XXX XXX XXX", 80),
    FRENCH_GUIANA("French Guiana","594","GF","", 81),
    ECUADOR("Ecuador","593","EC","XX XXX XXXX", 82),
    GUYANA("Guyana","592","GY","", 83),
    BOLIVIA("Bolivia","591","BO","X XXX XXXX", 84),
    GUADELOUPE("Guadeloupe","590","GP","XXX XX XX XX", 85),
    HAITI("Haiti","509","HT","", 86),
    SAINT_PIERRE_MIQUELON("Saint Pierre & Miquelon","508","PM","", 87),
    PANAMA("Panama","507","PA","XXXX XXXX", 88),
    COSTA_RICA("Costa Rica","506","CR","XXXX XXXX", 89),
    NICARAGUA("Nicaragua","505","NI","XXXX XXXX", 90),
    HONDURAS("Honduras","504","HN","XXXX XXXX", 91),
    EL_SALVADOR("El Salvador","503","SV","XXXX XXXX", 92),
    GUATEMALA("Guatemala","502","GT","X XXX XXXX", 93),
    BELIZE("Belize","501","BZ","", 94),
    FALKLAND_ISLANDS("Falkland Islands","500","FK","", 95),
    LIECHTENSTEIN("Liechtenstein","423","LI","", 96),
    SLOVAKIA("Slovakia","421","SK","XXX XXX XXX", 97),
    CZECH_REPUBLIC("Czech Republic","420","CZ","XXX XXX XXX", 98),
    MACEDONIA("Macedonia","389","MK","XX XXX XXX", 99),
    BOSNIA_HERZEGOVINA("Bosnia & Herzegovina","387","BA","XX XXX XXX", 100),
    SLOVENIA("Slovenia","386","SI","XX XXX XXX", 101),
    CROATIA("Croatia","385","HR","", 102),
    KOSOVO("Kosovo","383","XK","XXXX XXXX", 103),
    MONTENEGRO("Montenegro","382","ME","", 104),
    SERBIA("Serbia","381","RS","XX XXX XXXX", 105),
    UKRAINE("Ukraine","380","UA","XX XXX XX XX", 106),
    SAN_MARINO("San Marino","378","SM","XXX XXX XXXX", 107),
    MONACO("Monaco","377","MC","XXXX XXXX", 108),
    ANDORRA("Andorra","376","AD","XX XX XX", 109),
    BELARUS("Belarus","375","BY","XX XXX XXXX", 110),
    ARMENIA("Armenia","374","AM","XX XXX XXX", 111),
    MOLDOVA("Moldova","373","MD","XX XXX XXX", 112),
    ESTONIA("Estonia","372","EE","", 113),
    LATVIA("Latvia","371","LV","XXX XXXXX", 114),
    LITHUANIA("Lithuania","370","LT","XXX XXXXX", 115),
    BULGARIA("Bulgaria","359","BG","", 116),
    FINLAND("Finland","358","FI","", 117),
    CYPRUS("Cyprus","357","CY","XXXX XXXX", 118),
    MALTA("Malta","356","MT","XX XX XX XX", 119),
    ALBANIA("Albania","355","AL","XX XXX XXXX", 120),
    ICELAND("Iceland","354","IS","XXX XXXX", 121),
    IRELAND("Ireland","353","IE","XX XXX XXXX", 122),
    LUXEMBOURG("Luxembourg","352","LU","", 123),
    PORTUGAL("Portugal","351","PT","X XXXX XXXX", 124),
    GIBRALTAR("Gibraltar","350","GI","XXXX XXXX", 125),
    GREENLAND("Greenland","299","GL","XXX XXX", 126),
    FAROE_ISLANDS("Faroe Islands","298","FO","XXX XXX", 127),
    ARUBA("Aruba","297","AW","XXX XXXX", 128),
    ERITREA("Eritrea","291","ER","X XXX XXX", 129),
    SAINT_HELENA_290("Saint Helena","290","SH","XX XXX", 130),
    COMOROS("Comoros","269","KM","XXX XXXX", 131),
    SWAZILAND("Swaziland","268","SZ","XXXX XXXX", 132),
    BOTSWANA("Botswana","267","BW","XX XXX XXX", 133),
    LESOTHO("Lesotho","266","LS","XX XXX XXX", 134),
    MALAWI("Malawi","265","MW","77 XXX XXXX", 135),
    NAMIBIA("Namibia","264","NA","XX XXX XXXX", 136),
    ZIMBABWE("Zimbabwe","263","ZW","XX XXX XXXX", 137),
    REUNION("Réunion","262","RE","XXX XXX XXX", 138),
    MADAGASCAR("Madagascar","261","MG","XX XX XXX XX", 139),
    ZAMBIA("Zambia","260","ZM","XX XXX XXXX", 140),
    MOZAMBIQUE("Mozambique","258","MZ","XX XXX XXXX", 141),
    BURUNDI("Burundi","257","BI","XX XX XXXX", 142),
    UGANDA("Uganda","256","UG","XX XXX XXXX", 143),
    TANZANIA("Tanzania","255","TZ","XX XXX XXXX", 144),
    KENYA("Kenya","254","KE","XXX XXX XXX", 145),
    DJIBOUTI("Djibouti","253","DJ","XX XX XX XX", 146),
    SOMALIA("Somalia","252","SO","XX XXX XXX", 147),
    ETHIOPIA("Ethiopia","251","ET","XX XXX XXXX", 148),
    RWANDA("Rwanda","250","RW","XXX XXX XXX", 149),
    SUDAN("Sudan","249","SD","XX XXX XXXX", 150),
    SEYCHELLES("Seychelles","248","SC","X XX XX XX", 151),
    SAINT_HELENA("Saint Helena","247","SH","XXXX", 152),
    DIEGO_GARCIA("Diego Garcia","246","IO","XXX XXXX", 153),
    GUINEA_BISSAU("Guinea-Bissau","245","GW","XXX XXXX", 154),
    ANGOLA("Angola","244","AO","XXX XXX XXX", 155),
    CONGO_DEM_REP("Congo (Dem. Rep., 156)","243","CD","XX XXX XXXX", 156),
    CONGO_REP("Congo (Rep., 157)","242","CG","XX XXX XXXX", 157),
    GABON("Gabon","241","GA","X XX XX XX", 158),
    EQUATORIAL_GUINEA("Equatorial Guinea","240","GQ","XXX XXX XXX", 159),
    SAO_TOME_PRINCIPE("São Tomé & Príncipe","239","ST","XX XXXXX", 160),
    CAPE_VERDE("Cape Verde","238","CV","XXX XXXX", 161),
    CAMEROON("Cameroon","237","CM","XXXX XXXX", 162),
    CENTRAL_AFRICAN_REP("Central African Rep.","236","CF","XX XX XX XX", 163),
    CHAD("Chad","235","TD","XX XX XX XX", 164),
    NIGERIA("Nigeria","234","NG","", 165),
    GHANA("Ghana","233","GH","", 166),
    SIERRA_LEONE("Sierra Leone","232","SL","XX XXX XXX", 167),
    LIBERIA("Liberia","231","LR","", 168),
    MAURITIUS("Mauritius","230","MU","", 169),
    BENIN("Benin","229","BJ","XX XXX XXX", 170),
    TOGO("Togo","228","TG","XX XXX XXX", 171),
    NIGER("Niger","227","NE","XX XX XX XX", 172),
    BURKINA_FASO("Burkina Faso","226","BF","XX XX XX XX", 173),
    COTE_DIVOIRE("Côte d`Ivoire","225","CI","XX XXX XXX", 174),
    GUINEA("Guinea","224","GN","XXX XXX XXX", 175),
    MALI("Mali","223","ML","XXXX XXXX", 176),
    MAURITANIA("Mauritania","222","MR","XXXX XXXX", 177),
    SENEGAL("Senegal","221","SN","XX XXX XXXX", 178),
    GAMBIA("Gambia","220","GM","XXX XXXX", 179),
    LIBYA("Libya","218","LY","XX XXX XXXX", 180),
    TUNISIA("Tunisia","216","TN","XX XXX XXX", 181),
    ALGERIA("Algeria","213","DZ","XXX XX XX XX", 182),
    MOROCCO("Morocco","212","MA","XX XXX XXXX", 183),
    SOUTH_SUDAN("South Sudan","211","SS","XX XXX XXXX", 184),
    IRAN("Iran","98","IR","XXX XXX XXXX", 185),
    MYANMAR("Myanmar","95","MM","", 186),
    SRI_LANKA("Sri Lanka","94","LK","XX XXX XXXX", 187),
    AFGHANISTAN("Afghanistan","93","AF","XXX XXX XXX", 188),
    PAKISTAN("Pakistan","92","PK","XXX XXX XXXX", 189),
    INDIA("India","91","IN","XXXXX XXXXX", 190),
    TURKEY("Turkey","90","TR","XXX XXX XXXX", 191),
    CHINA("China","86","CN","XXX XXXX XXXX", 192),
    VIETNAM("Vietnam","84","VN","", 193),
    SOUTH_KOREA("South Korea","82","KR","", 194),
    JAPAN("Japan","81","JP","XX XXXX XXXX", 195),
    THAILAND("Thailand","66","TH","X XXXX XXXX", 196),
    SINGAPORE("Singapore","65","SG","XXXX XXXX", 197),
    NEW_ZEALAND("New Zealand","64","NZ","", 198),
    PHILIPPINES("Philippines","63","PH","XXX XXX XXXX", 199),
    INDONESIA("Indonesia","62","ID","", 200),
    AUSTRALIA("Australia","61","AU","XXX XXX XXX", 201),
    MALAYSIA("Malaysia","60","MY","", 202),
    VENEZUELA("Venezuela","58","VE","XXX XXX XXXX", 203),
    COLOMBIA("Colombia","57","CO","XXX XXX XXXX", 204),
    CHILE("Chile","56","CL","X XXXX XXXX", 205),
    BRAZIL("Brazil","55","BR","XX XXXXX XXXX", 206),
    ARGENTINA("Argentina","54","AR","", 207),
    CUBA("Cuba","53","CU","XXXX XXXX", 208),
    MEXICO("Mexico","52","MX","", 209),
    PERU("Peru","51","PE","XXX XXX XXX", 210),
    GERMANY("Germany","49","DE","", 211),
    POLAND("Poland","48","PL","XXX XXX XXX", 212),
    NORWAY("Norway","47","NO","XXXX XXXX", 213),
    SWEDEN("Sweden","46","SE","XX XXX XXXX", 214),
    DENMARK("Denmark","45","DK","XXXX XXXX", 215),
    UNITED_KINGDOM("United Kingdom","44","GB","XXXX XXXXXX", 216),
    AUSTRIA("Austria","43","AT","", 217),
    Y_LAND("Y-land","42","YL","", 218),
    SWITZERLAND("Switzerland","41","CH","XX XXX XXXX", 219),
    ROMANIA("Romania","40","RO","XXX XXX XXX", 220),
    ITALY("Italy","39","IT","", 221),
    HUNGARY("Hungary","36","HU","XXX XXX XXX", 222),
    SPAIN("Spain","34","ES","XXX XXX XXX", 223),
    FRANCE("France","33","FR","X XX XX XX XX", 224),
    BELGIUM("Belgium","32","BE","XXX XX XX XX", 225),
    NETHERLANDS("Netherlands","31","NL","X XX XX XX XX", 226),
    GREECE("Greece","30","GR","XXX XXX XXXX", 227),
    SOUTH_AFRICA("South Africa","27","ZA","XX XXX XXXX", 228),
    EGYPT("Egypt","20","EG","XX XXXX XXXX", 229),
    KAZAKHSTAN("Kazakhstan","7","KZ","XXX XXX XX XX", 230),
    RUSSIAN_FEDERATION("Russian Federation","7","RU","XXX XXX XXXX", 231),
    PUERTO_RICO("Puerto Rico","1","PR","XXX XXX XXXX", 232),
    DOMINICAN_REP("Dominican Rep.","1","DO","XXX XXX XXXX", 233),
    CANADA("Canada","1","CA","XXX XXX XXXX", 234),
    USA("USA","1","US","XXX XXX XXXX", 235)
}